config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :user_addresses
  get 'home/index'
  get 'sessions/signin'
  get 'sessions/signup'
  post 'sessions/create'
  post 'sessions/login'
  
  post 'sessions/signout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, :email, presence: true
  validates :email, uniqueness: true

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :current_user

  def authenticate
    redirect_to sessions_signin_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:current_user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate

  def signin
  end

  def signup
  end

  def signout
  end

  def create
    user = User.new(session_params)
    if user.save
      session[:current_user_id] = user.id
      redirect_to home_index_path
      return
    end
    render json: {}, status: :unauthorized
  end 

  def login
    user = User.find_by(email: session_params[:email])
    
    if user && user.authenticate(session_params[:password])
      session[:current_user_id] = user.id
      redirect_to home_index_path
      return
    end
    render json: {}, status: :unauthorized 
  end

  private

  def session_params
    params.require(:session).permit(:name, :email, :password, :password_confirmation )
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :descripiton, :completed, :date)
    end
end

app/controllers/user_addresses_controller.rb
class UserAddressesController < ApplicationController
  before_action :set_user_address, only: %i[ show edit update destroy ]

  # GET /user_addresses or /user_addresses.json
  def index
    @user_addresses = UserAddress.all
  end

  # GET /user_addresses/1 or /user_addresses/1.json
  def show
  end

  # GET /user_addresses/new
  def new
    @user_address = UserAddress.new
  end

  # GET /user_addresses/1/edit
  def edit
  end

  # POST /user_addresses or /user_addresses.json
  def create
    @user_address = UserAddress.new(user_address_params)

    respond_to do |format|
      if @user_address.save
        format.html { redirect_to user_address_url(@user_address), notice: "User address was successfully created." }
        format.json { render :show, status: :created, location: @user_address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_addresses/1 or /user_addresses/1.json
  def update
    respond_to do |format|
      if @user_address.update(user_address_params)
        format.html { redirect_to user_address_url(@user_address), notice: "User address was successfully updated." }
        format.json { render :show, status: :ok, location: @user_address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_addresses/1 or /user_addresses/1.json
  def destroy
    @user_address.destroy

    respond_to do |format|
      format.html { redirect_to user_addresses_url, notice: "User address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_address
      @user_address = UserAddress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_address_params
      params.require(:user_address).permit(:street, :number, :city, :state, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/user_addresses_helper.rb
module UserAddressesHelper
end

app/views/home/index.html.erb
<h1>Welcome <%= current_user.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TDDWithRspec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :descripiton, style: "display: block" %>
    <%= form.text_field :descripiton %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Title:</strong>
    <%= todo.title %>
  </p>

  <p>
    <strong>Descripiton:</strong>
    <%= todo.descripiton %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= todo.completed %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= todo.date %>
  </p>

</div>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todos</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <%= render todo %>
    <p>
      <%= link_to "Show this todo", todo %>
    </p>
  <% end %>
</div>

<%= link_to "New todo", new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>

app/views/user_addresses/_form.html.erb
<%= form_with(model: user_address) do |form| %>
  <% if user_address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_address.errors.count, "error") %> prohibited this user_address from being saved:</h2>

      <ul>
        <% user_address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_addresses/_user_address.html.erb
<div id="<%= dom_id user_address %>">
  <p>
    <strong>Street:</strong>
    <%= user_address.street %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= user_address.number %>
  </p>

  <p>
    <strong>City:</strong>
    <%= user_address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= user_address.state %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_address.user_id %>
  </p>

</div>

app/views/user_addresses/edit.html.erb
<h1>Editing user address</h1>

<%= render "form", user_address: @user_address %>

<br>

<div>
  <%= link_to "Show this user address", @user_address %> |
  <%= link_to "Back to user addresses", user_addresses_path %>
</div>

app/views/user_addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User addresses</h1>

<div id="user_addresses">
  <% @user_addresses.each do |user_address| %>
    <%= render user_address %>
    <p>
      <%= link_to "Show this user address", user_address %>
    </p>
  <% end %>
</div>

<%= link_to "New user address", new_user_address_path %>

app/views/user_addresses/new.html.erb
<h1>New user address</h1>

<%= render "form", user_address: @user_address %>

<br>

<div>
  <%= link_to "Back to user addresses", user_addresses_path %>
</div>

app/views/user_addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_address %>

<div>
  <%= link_to "Edit this user address", edit_user_address_path(@user_address) %> |
  <%= link_to "Back to user addresses", user_addresses_path %>

  <%= button_to "Destroy this user address", @user_address, method: :delete %>
</div>